# Generated by Django 4.1.2 on 2024-10-23 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1_mis_ofertas', '0002_remove_infousuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
