# Generated by Django 4.1.2 on 2024-10-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_mis_ofertas', '0003_alter_infousuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='infousuario',
            name='apellido',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='infousuario',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
    ]
