# Generated by Django 4.1.2 on 2024-10-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_mis_ofertas', '0005_alter_infousuario_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='infousuario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
