# Generated by Django 5.1.2 on 2024-10-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_mis_ofertas', '0007_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='Nada', upload_to='img'),
        ),
    ]
